services:
  web:
    build:
      context: .
      dockerfile: dockerizer/Dockerfile
    image: miaumiauweb:latest
    container_name: miaumiauweb
    restart: unless-stopped
    ports:
      - "80:80"
